version: '2'
services:
  database:
    image: "mysql:5.7"
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=5ecret
     - MYSQL_USER=17high
     - MYSQL_PASSWORD=17high
     - MYSQL_DATABASE=17high
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
  17high:
      image: "tw-wh-devops/17high"
      ports:
       - "8080:8080"
      environment:
       - MYSQL_HOST=database
       - MYSQL_DATABASE=17high
       - MYSQL_USER=17high
       - MYSQL_PASSWORD=17high
      links:
       - database
  backup:
    image: "schickling/mysql-backup-s3"
    environment:
     - S3_ACCESS_KEY_ID=AK1IAJI55LQVYZNTGAATA
     - S3_SECRET_ACCESS_KEY=ipwvhaP+m5aa5hfmRit75Tk7B5wYwEu1Rvm0o7bEV5
     - S3_BUCKET=17high
     - MYSQLDUMP_DATABASE=17high
     - MYSQL_HOST=database
     - MYSQL_USER=17high
     - MYSQL_PASSWORD=17high
     - S3_REGION=ap-northeast-1
     - MULTI_FILES=yes
     - SCHEDULE=@daily
    links:
      - database
